package com.circus.nativenavs.util

const val PREF = "pref"
const val USER_ID = "userId"
const val EMAIL = "email"
const val AGE = "age"
const val LANGUAGE = "language"
const val IS_NAV = "isNav"
const val ENABLED_NOTI = "enabledNoti"
const val ACCESSTOKEN = "accessToken"
const val REFRESHTOKEN = "refreshToken"
const val FCM_TOKEN = "fcmToken"
const val LOGOUT = "logout"
const val NATIVENAVS_URL = "https://i11d110.p.ssafy.io/api/"
const val CHANNEL_ID = "NativeNavs_Channel"
const val WEBURL = "https://i11d110.p.ssafy.io/"